import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import clsx from "clsx";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Dripbit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="dark">
      <body
        className={clsx(
          "dark min-h-screen font-sans antialiased",
          poppins.variable
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
